st="Welcome, in ,Gorakhpur"
print(st)
print("no of character=",len(st))
s=st.capitalize()
print(s)
print(st.swapcase())
print(st.title())
print(st.lower())
print(st.upper())
print(st.split(','))
print(st.find('in'))
print(st.find('o'))
print(st.count('o'))
print(st.endswith('Gorakhpur'))
print(st.replace('Gorakhpur','lko'))
print(st.replace('o','m'))
name=input("enter your name")
print(name)
print(name.strip())
print(name.rstrip())
print(name.lstrip())
print(name.isalpha())
age=input("enter your age")
print(age)
print(age.isdigit())
empid=input("enter your empid")
print(empid)
print(empid.isalnum())



